---
- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /Users/anapedra/Downloads/terraform-learn-feature-eks/kubeconfig_myapp-eks-cluster
    - name: Deploy nginx my-app
      kubernetes.core.k8s:
        src: ~/demo-projects/K8s-Files/nginx-config.yaml
        state: present
        kubeconfig:  /Users/anapedra/Downloads/terraform-learn-feature-eks/kubeconfig_myapp-eks-cluster
        namespace: my-app

